### ISSUE TITLE
unknown class, you need to register this class with lua-intf first by using LuaBinding

### ISSUE THREAD

**Issue by nghack** [SteveKChiu/lua-intf#100]
Errors:
unknown class, you need to register this class with lua-intf first by using LuaBinding
C++:
other DLL, have no source. This is just a example:
int LuaApp::GetWndHandle(lua_State* luaState){
	lua_pushlightuserdata(luaState, LuaApp.hWnd);
	return 1;
}
My source:
HWND OSShell::GetParent(HWND hWnd) {
        DWORD ret = ::GetParent(hWnd);
        return ret;
    }
LuaBinding(luaState)
        .beginModule("OSShell")
        .addFunction("GetParent", &OSShell::GetParent)
        .endModule();
Lua:
function OnCreate(hostwnd)
    local hwnd = hostwnd:GetWndHandle()
    local parent = OSShell.GetParent(hwnd)
    ... ...
end

How do I change my source?
Thanks for help!

**Comment by SteveKChiu** [comment]
LuaBinding does not know how to handle `HWND` type, thus give the error.
You need to either use `LuaBinding.beginClass` or `LuaTypeMapping` to add the mapping for `HWND`.

**Comment by SteveKChiu** [comment]
It seems to be resolved.
