### ISSUE TITLE
Question: How to pass existing shared_ptr object to Lua ?

### ISSUE THREAD

**Issue by inDigiNeous** [SteveKChiu/lua-intf#101]
Hey Steve, thanks again for creating LuaIntf, been using with my C++ project.

I have one question I hoped you could answer. 

How can I pass an already existing object instance from C++ to Lua ?

I have a class called ObjRender, which I make an instance and want to pass to the lua script
I use the std::shared_ptr and have specified in namespace LuaIntF to use the std::shared_ptr

I create my class instance in C++ like this:

```c++
	controller = std::make_shared<ObjRender>();
```

Then I register the class with luaintf:

```c++
	LuaIntf::LuaBinding(_lua).beginClass<ObjRender>("ObjRender")
		.addConstructor(LUA_ARGS())
		.addFunction("printStatus",  		&ObjRender::printStatus)
	.endClass();
```

I can succesfully use this class if I create the instance on Lua side.
But I cannot seem to figure out how to pass the C++ instance shared ptr to the lua script.

What I would wish to do is set it as a global value in lua.
I've tried this:

```c++
	lua_pushlightuserdata(_lua, (void*)&controller);
	lua_setglobal(_lua, "controller");
```

But I guess it takes more than that just to call an object, because when I then try to do this:

```lua
	controller:printStatus()
```
It just gives an '[C++] Failed calling 'main': main.lua:14: attempt to index a userdata value (global 'controller')' error.

My aim is to create the main controller class on the C++ side, then just pass pointer of that to the lua script so I can control the main program logic through Lua.

What would be the preferred way of doing this with LuaIntf ? Thank you for any direction, as I'm struggling to understand how to do this now.

**Comment by SteveKChiu** [comment]
First you need to make sure you import std::shared_ptr to LuaBinding by using `LUA_USING_SHARED_PTR_TYPE(std::shared_ptr)`, then you just use `LuaIntf::Lua::setGlobal(lua_state, "controller", controller)` to register the object.

It is important to use `LuaIntf::Lua::setGlobal`, thus LuaBinding would add necessary conversion for you (by construct correct userdata, etc...).

**Comment by inDigiNeous** [comment]
Thank you @SteveKChiu, I got it working. Didn't realize the setGlobal method could be used for this. Thanks!

**Comment by SteveKChiu** [comment]
It seems to be resolved.
