### ISSUE TITLE
Unresolved external problem building with VS2015

### ISSUE THREAD

**Issue by astone-ke** [SteveKChiu/lua-intf#102]
Building lua-intf with 5.3 on VS2015 on my application produces unresolved external symbol errors.

I have a lua 5.3 library (compiled with /TP to force it to build using C++ exceptions), I have a main exe (also compiled with /TP).  Additional include paths include both the lua5.3 src directory and the lua-intf directory.  Input to the C++ linker for my exe includes a reference to the lua 5.3 lib created with the project it depends on.

In my test application I have the following code:

#include "LuaIntf\LuaIntf.h"
using namespace LuaIntf;

int main() {
	LuaState lua;
	lua = LuaIntf::LuaState::newState();
       return 0;
}

This code produces unresolved external errors (C2019 in VS2015) referencing the functions luaL_loadfilex, panic and luaO_tostring.

LUAINTF_LINK_LUA_COMPILED_IN_CXX is set to "1" to build under C++.

Any ideas on what is causing this error or how to resolve it?

**Comment by SteveKChiu** [comment]
1. make sure you define LUAINTF_LINK_LUA_COMPILED_IN_CXX in the right place, e.g. placed in the project setting, or explicitly define it just before include LuaIntf.h

2. Do not include "lua.hpp", which will force lua function into extern "C" space.

**Comment by astone-ke** [comment]
OK, I have added the line "#define LUAINTF_LINK_LUA_COMPILED_IN_CXX 1" right before including LuaIntf.h, and there are no references to lua.hpp anywhere in the code.  I am still seeing these linker errors.

Any other ideas about what might be going on?

**Comment by astone-ke** [comment]
OK, I figured out what the problem was.  The Lua 5.3 library I was building against was set up to build under VS2013.  By upgrading the compiler and run time libraries to use VS2015 libs lua-intf compiles and links just fine, thank you!
