### ISSUE TITLE
(question) Changing a value from lua stack

### ISSUE THREAD

**Issue by SigilMMO** [SteveKChiu/lua-intf#103]
To preface my question I'd like to say I'm very pleased with this library, it's extensively useful and I love using it.
That said, I'm having an issue. As per the documentation, my objects that Lua uses are by C++ pointer, so that I can control the lifetime of the object from C++ and it doesn't get garbage collected. This works as intended, although I'm wondering how exactly I safely handle the end of a C++ object's life.
I have a 'delete' method in one of my classes which basically deletes the C++ object from memory - referencing it again in the Lua script will naturally cause a segmentation fault. My question to you is, how do I set the value to nil after I'm done deleting it?
I've tried something like this:

        // ref is the LuaRef to the object passed on the stack, ie
        // obj:delete()
        // where ref=obj
        LuaIntf::LuaState lua=L;
        LuaIntf::LuaRef reg=LuaRef::registry(L);

        for(auto& i : reg) {
            LuaRef value = i.value<LuaRef>();

            if(value.type() == LuaTypeID::LIGHTUSERDATA || value.type() == LuaTypeID::USERDATA) {
                if(value.isIdenticalTo(ref)) {
                    int key = i.key<int>();
                    reg.set(key, LuaRefValue(L,nullptr) );
                    // or reg.remove(key)
                }
            }
        }

However `LuaRef::registry(L)` evidently returns a copy, the changes aren't saved.

**Comment by SteveKChiu** [comment]
If you export the object as global variable (by using Lua::setGlobal), then you can just use Lua::setGlobal again to set it to nil. Otherwise, I am not sure there is a good way to clear the reference, because you can not control the life cycle of lua object.

**Comment by SteveKChiu** [comment]
It seems to be resolved. Please reopen if you have more questions.
