### ISSUE TITLE
Compile error with function with argument of char*

### ISSUE THREAD

**Issue by yihuang** [SteveKChiu/lua-intf#104]
This is the program to show this problem: https://gist.github.com/yihuang/dabd623fd025f37cdd1f
If I change the "char*" to "unsigned char*", the compile error disappear.

**Comment by SteveKChiu** [comment]
char* mapping is inherently dangerous, `lua-intf` used to treat it as const char* for string mapping, but some of the last commits break the mapping.

I think it would be better for `lua-intf` to remove char* mapping entirely, please do not use char*, or unsigned char*, or pointer to other primitive types. Write a wrapper to convert the pointer to value or to array explicitly to match your function.

And even you can get the code compiled with unsigned char*, it won't run properly, I think `lua-intf` will complain as soon as you run the function.

**Comment by yihuang** [comment]
I see, thanks.
