### ISSUE TITLE
Is it possible to expose a function which accepts a lua function as callback.

### ISSUE THREAD

**Issue by yihuang** [SteveKChiu/lua-intf#105]
Possibly implemented with ``luaL_ref``, to store the lua function as a ``int`` value at the c++ side.

**Comment by SteveKChiu** [comment]
You can use LuaRef as parameter, which can map to lua function (or any other lua values, tables)

LuaRef is a wrapper class for the luaL_ref functions.

**Comment by yihuang** [comment]
Thanks.
