### ISSUE TITLE
lua error when binding a function returns pointer.

### ISSUE THREAD

**Issue by yihuang** [SteveKChiu/lua-intf#108]
I've met this problem when trying to bind a method which returns a pointer to a buffer. I expect lua side get a userdata which can be passed back to c++ side later, but it cause lua error. I find it difficult to trace down to specific location of source which trigger this error.
I've created a gist to show this problem:
https://gist.github.com/yihuang/63290daa3e2fb607fee2

**Comment by SteveKChiu** [comment]
You can not use arbitrary data type with `lua-intf`, any data type must be registered first (except primitive types)

`void*` is not supported by default, you can add LuaTypeMapping by yourself if needed, but I think it is too dangerous to enable that for scripting.

**Comment by SteveKChiu** [comment]
If you have more questions, please re-open this issue.
