### ISSUE TITLE
Question: How to create shared_ptr inside lua script and pass to C++ ?

### ISSUE THREAD

**Issue by inDigiNeous** [SteveKChiu/lua-intf#109]
I'm just gonna ask this, as I have no idea how the interaction between shared_ptr's happen between lua and C++.

I can now happily get shared_ptrs from C++ side to the Lua script.
But how can I create shared_ptr in my .lua script and pass it to the C++ side ?

Right now, I have for example this:

```C++
	LuaIntf::LuaBinding(_lua).beginClass<PolyConfig>("PolyConfig")
		.addConstructor(LUA_ARGS())
		.addFunction("printValues",		&PolyConfig::printValues)
	.endClass();

	LuaIntf::LuaBinding(_lua).beginClass<Poly>("Poly")
		.addConstructor(LUA_ARGS())
		.addFunction("init",			&Poly::init)
		.addFunction("setAsRoot",		&Poly::setAsRoot)
		.addFunction("setConfig", 		&Poly::setConfig,			LUA_ARGS(shared_ptr<PolyConfig>))
		.addFunction("setLineShader", 		&Poly::setLineShader,			LUA_ARGS(shared_ptr<PSIGLShader>))
		.addFunction("setPointShader", 		&Poly::setPointShader,			LUA_ARGS(shared_ptr<PSIGLShader>))
	.endClass();
```

In my Lua script I do this:

```lua
	local poly_cfg = PolyConfig()
	poly_cfg:printValues()

	local poly = Poly()
	poly:setConfig(poly_cfg)
	poly:setLineShader(lineShader)
	poly:setPointShader(pointShader)
	poly:setAsRoot()
	poly:init()
```

The poly:setConfig(poly_cfg) fails with

"[C++] Failed calling 'main': main.lua:47: is not shared object"

Which I understand, the local poly_cfg is not created as shared_ptr.
Is there an easy way to cast or create it as a shared_ptr on the lua side ?

The shaders work, as I am creating them on the C++ side and returning from a function as shared_ptr.

I hope you can help me with this. Thank you!

**Comment by SteveKChiu** [comment]
`.addConstructor(LUA_ARGS())` will create a value object (i.e. allocate userdata with size == sizeof(object), and init the object there)

If you want to create lua object with shared_ptr inside the userdata, you can:

1. use ``.addConstructor(LUA_SP(shared_ptr<Object>))`
2. or register a static method whose return value is `shared_ptr<Object>`

**Comment by inDigiNeous** [comment]
Thanks for the quick reply! If I ever get this software shipped with this, I'll be sure to donate something to you :) 

Got it working with

```
		.addConstructor(LUA_SP(shared_ptr<PolyConfig>), LUA_ARGS())
```

Ps. Maybe helpful would be compile all the questions here to a FAQ or something!
