### ISSUE TITLE
VisualStudio 2015 warning, 'lua_Interger to int' possible loss of data

### ISSUE THREAD

**Issue by fordcars** [SteveKChiu/lua-intf#110]
When compiling on VisualStudio 2015, you get a bunch of errors from one function, tableLen(), stating that there is a conversion from 'lua_interger' to 'int', possible loss of data.

LuaState.h, line 588
```
    int tableLen(int table_idx) const
        { return luaL_len(L, table_idx); }
```

**Comment by fordcars** [comment]
It is the only function doing this, it's just an annoying warning. Nothing big :)

**Comment by SteveKChiu** [comment]
Thanks, I remove the warning in the new commit.
