### ISSUE TITLE
VisualStudio 2015 unable to access CppBindClass::bind()

### ISSUE THREAD

**Issue by fordcars** [SteveKChiu/lua-intf#111]
When compiled with VisualStudio 2015, I got an error saying that `CppBindClass::bind()` called from `LuaBinding` in file `CppBindModule.h` at line `671` was inaccessible since it was private. I think it is because `CppBindClass` does not include `LuaBinding` as a friend class.

**Comment by SteveKChiu** [comment]
Thanks, I forgot to add this in last LuaBinding refactoring.
