### ISSUE TITLE
Call a Lua function from C++?

### ISSUE THREAD

**Issue by fordcars** [SteveKChiu/lua-intf#112]
Hi,

I was wondering if there is a way to call a Lua function from C++, and be able to give arguments to it?
Right now I am using `luaState.doString("foo()")` to cheaply call Lua functions, but I can't give arguments.

Thanks

**Comment by JuJuBoSc** [comment]
LuaRef func(L, "module.method");
    func(1, "yes", true);

**Comment by SteveKChiu** [comment]
This seems to be resolved, please re-open this issue if needed.
