### ISSUE TITLE
How to bind a class with 2D array to a variable reference

### ISSUE THREAD

**Issue by astone-ke** [SteveKChiu/lua-intf#114]
I have a class in C++ with a data member representing a 4x4 matrix that looks like this:

union { 
float m[4][4]; 
float v[16];
};

I have tried binding a variable reference to this data using:
.addVariableRef("m", &Matrix4::m)

but this fails with the error, "cannot convert argument 2 from 'overloaded function type' to 'const float *const *"

I understand how to bind std::map and std::vector members of a C++ class to lua, but is it possible to bind up a raw 2D array?  I'm aiming for lua syntax that's like:

mat = Matrix4()
mat[0][2] = 42.0

I can bind a setter and getter so that the syntax looks like
mat:set(0, 2, 42.0)

but this is somewhat cumbersome and I'll have to modify my matrix4 class, which I'd like to avoid.  I'd rather use a property or variable reference.  Is that possible using lua-intf?

**Comment by SteveKChiu** [comment]
The only way I can think about is to write the getter and setter by your self, it is easy to that with help of c++11 lambda.

For example, you can do this:

````
LuaBinding(L).beginClass<Matrix4>("Matrix4")
...
    .addFunction("get", [](Matrix4* p, int i0, int i1) -> float {
        return p->m[i0][i1];
    })
    .addFunction("set", [](Matrix4* p, int i0, int i1, float v) {
        p->m[i0][i1] = v;
    })
    .endClass();
````

**Comment by astone-ke** [comment]
That's not precisely what I was looking for but it's good enough to make the project work.

Thank you for your reply!
