### ISSUE TITLE
Support free functions as class constructors

### ISSUE THREAD

**Issue by ibachar** [SteveKChiu/lua-intf#116]
Hi,

I think it would be great if it was possible to supply a free function as a class constructor.
This way we could implement constructors which take varying types / number of arguments.

Thanks

**Comment by SteveKChiu** [comment]
Please see the read me file, under *Using custom deleter* secrion.

**Comment by ibachar** [comment]
I've seen it but I'm talking about custom constructors and not destructors or am I missing something?

**Comment by EugeneKozlov** [comment]
Yes, you have missed.

**Comment by ibachar** [comment]
OK, reading again, I think that's what factory is meant to do. @EugeneKozlov thanks for being so informative with your answer
