### ISSUE TITLE
Build error with android ndk.

### ISSUE THREAD

**Issue by yihuang** [SteveKChiu/lua-intf#117]
I'm using lua-intf to make OpenGL api to lua, but it fails to compile under android ndk. 
The code is like:
```
LuaBinding(L).beginModule("gl")
   .addFunction("glActiveTexture", &glActiveTexture)
.endModule();
```

The error message is like:

```
jni/../../../libs/LuaIntf/impl/CppBindModule.h:447:62: error: implicit instantiation of
      undefined template 'LuaIntf::CppBindMethod<void (*)(unsigned int)
      __attribute__((pcs("aapcs"))), void (*)(unsigned int) __attribute__((pcs("aapcs"))),
      1, 0, void>'
        m_meta.rawset(name, LuaRef::createFunction(state(), &CppProc::call, CppPro...
                                                             ^
jni/../../../lua/luagl.cpp:808:10: note: in instantiation of function template
      specialization 'LuaIntf::CppBindModule::addFunction<void (*)(unsigned int)
      __attribute__((pcs("aapcs")))>' requested here
        .addFunction("glActiveTexture", &glActiveTexture)
```

After I change it to ``.addFunction("glActiveTexture", LUA_FN(void, glActiveTexture, GLenum))``, the error message becomes:
```
jni/../../../lua/luagl.cpp:808:41: error: static_cast from 'void (*)(GLenum)
      __attribute__((pcs("aapcs")))' to 'void (*)(GLenum)' is not allowed
        .addFunction("glActiveTexture", LUA_FN(void, glActiveTexture, GLenum))
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
jni/../../../libs/LuaIntf/impl/CppArg.h:50:27: note: expanded from macro 'LUA_FN'
#define LUA_FN(r, m, ...) static_cast<r(*)(__VA_ARGS__)>(&m)
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I figure it's not a bug of lua-intf, but have something to do with ``__attribute__((pcs("aapcs")))``, I don't find much information about this on google, can you enlighten me on this?

PS. create a wrapper function for it seems working, but need to create wrapper function for all OpenGL api is quite annoying. Is it solvable in lua-intf?

**Comment by SteveKChiu** [comment]
pcs("aapcs") has something to do with ARM calling convention (about hard float I think), I am afraid there is no way except adding a wrapper function. You can use c++ lambda to wrap the function, that is small and simple enough.

Another way is maybe you can compile your code with hard float enabled, so there is no mismatch with calling convention.

**Comment by yihuang** [comment]
I've found tools like glad(https://github.com/Dav1dde/glad), I'll try to use that and see what comes out, anyway, it's not an issue of lua-intf, so I'm closing it.
Thanks for you suggestion.
