### ISSUE TITLE
Segmentation fault at gcc version 5.2.1

### ISSUE THREAD

**Issue by satoren** [SteveKChiu/lua-intf#118]
I'm writing benchmark.
```
	lua_State *state = luaL_newstate(); luaL_openlibs(state);
	luaL_dostring(state, "lua_function=function(i)return i;end");
	LuaIntf::LuaRef f(state, "lua_function");
	
	std::string teststring = "testtext";
	for (int i = 0; i < 1000000; ++i)
	{
		std::string result = f.call<std::string>(teststring);
		if (result != teststring) { throw std::logic_error(""); }
	}
	lua_close(state);
```
this code crashed at gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)　with '-O3 -DNDEBUG -std=c++14'
with lua5.2

Do you know what's bad?

**Comment by SteveKChiu** [comment]
The code seems OK, and I am able to run it without problem with clang.
Try to change cflags to O2 instead.

**Comment by satoren** [comment]
ah. I'm sorry. bad is code.
execute LuaRef destructor after lua_close(state);
