### ISSUE TITLE
Mixing "__index","__newindex" functions inheritance and properties.

### ISSUE THREAD

**Issue by stdgregwar** [SteveKChiu/lua-intf#121]
I have the following binding code

```C++
.beginClass<Component>("Component")
.addFunction("__index", &Component::getPropRef)
.addFunction("__newindex", &Component::setPropRef)
.endClass()

.beginExtendClass<TransformComponent,Component>("TransformComponent")
.addFunction("__index", &Component::getPropRef)
.addFunction("__newindex", &Component::setPropRef)
.addPropertyReadOnly("worldPos",&TransformComponent::getWorldPos)
.endClass()
```

**First problem :** I've been forced to redefine the metamethods in the child class for them to be available. Is it normal?

**Second problem :** the worldPos property is somehow shadowed by the __index metamethod and is thus unavailable.

Issue or am I doing something wrong?

**Comment by SteveKChiu** [comment]
Unfortunately you can not override __index and __newindex, because LuaIntf will use its own version to access member property/method.

Override __index/__newindex will cause LuaIntf to malfunction.
