### ISSUE TITLE
CppObject::allocate crash with shared_ptr class

### ISSUE THREAD

**Issue by N-01** [SteveKChiu/lua-intf#124]
Hi, not sure how to report this problem. It happens, when i get a LuaRef to one of the existing tables and try to create a field containing bound C++ class withing it. It worked for quite a while and now i get a crash after some non-relevant changes. Just going straight to code:

```
Script& ScriptSystem::addGameObject(shared_ptr<Body> target)
{
	auto& script = target->addComponent<Script>();
	LuaRef componentClass(luaState, "GameObject");
	script.ref = componentClass.dispatch<LuaRef>("spawn"); //spawn an instance of GameObject class table
    //assign entity reference as "body" field
	script.ref["body"] = target; << Unhandled exception at 0x00000003EA325A4E (ucrtbase.dll) in N2.exe: Fatal program exit requested.

	return script;
}
```

//Body class binding code
```
LUA_USING_SHARED_PTR_TYPE(std::shared_ptr)
...
LuaIntf::LuaBinding(luaState).beginClass<Body>("Body")
		.addConstructor(LUA_ARGS())
		.addConstructor(LUA_SP(std::shared_ptr<Body>), LUA_ARGS())
		.addFunction("getComponent", &Body::getComponentLua)
		.addFunction("getScriptComponent", &Body::getScriptComponent)
		.addFunction("addComponent", &Body::addComponentLua)
		.addFunction("hasComponent", &Body::hasComponentLua)
		.addFunction("hasScriptComponent", &Body::hasScriptComponent)
		.endClass();
```

//Call stack
```
Exception at line lua_setmetatable(L, -2);
LuaIntf::CppObject::allocate<LuaIntf::CppObjectValue<std::shared_ptr<Body> > >(lua_State * L, void * class_id) Line 77	C++
LuaIntf::CppObjectValue<std::shared_ptr<Body> >::pushToStack(lua_State * L, const std::shared_ptr<Body> & obj, bool is_const) Line 307	C++
LuaIntf::LuaCppObjectFactory<std::shared_ptr<Body>,std::shared_ptr<Body>,0,0>::push(lua_State * L, const std::shared_ptr<Body> & obj, bool is_const) Line 436	C++
LuaIntf::LuaClassMapping<std::shared_ptr<Body>,0,0>::push(lua_State * L, const std::shared_ptr<Body> & t) Line 497	C++
LuaIntf::Lua::push<std::shared_ptr<Body> >(lua_State * L, const std::shared_ptr<Body> & v) Line 62	C++
LuaIntf::LuaTableRef::operator=<std::shared_ptr<Body> >(const std::shared_ptr<Body> & value) Line 117	C++
ScriptSystem::addGameObject(std::shared_ptr<Body> target) Line 347	C++
```

All the LuaRef's involved are valid. "componentClass.dispatch<LuaRef>("spawn")" gets called succesfully. Also, if i use reference instead of shared_ptr, it seems to work fine.
Can someone give me a clue on what am i doing wrong?

LuaIntf::LuaCppObjectFactory<std::shared_ptr<Body>,std::shared_ptr<Body>,0,0>

this parts seems really fishy to me, second to last template parameter is 0 as if T is not a shared_ptr.

**Comment by SteveKChiu** [comment]
Every property of class need to be declared in LuaBinding, otherwise LuaBinding don't know how to deal with the mapping. In your case, it seems "body" field is not known to the class (I am not sure, since you does not show the GameObject class)

BTW, you can only have one addConstructor, the later one will replace the former one, there is no override handling for constructors/functions.

**Comment by N-01** [comment]
The "body" field you mentioned is queried from something that is not a c++ class. It's from lua table, and i assign c++ class instance to it. I solved the problem, it was buried in the LUA_USING_SHARED_PTR_TYPE(std::shared_ptr) macro. At some point i included LuaIntf.hpp in some header, where that macro wasn't defined yet. And, i guess, that caused instantiation of some template before (LuaClassMapping, i guess) before appropriate CppObjectTraits was defined. It was hell of the bug to catch.

P.S. Thank you for info on constructors, does that mean we cannot have overloaded constructors or you meant default constructor? If it's former, could you provide reasoning behind that?

**Comment by SteveKChiu** [comment]
You can not have overloaded constructors or functions, the LuaIntf dispatch can not handle this.
It is simply too costly to implement constructors/functions overloading, as the only way is to determined from argument types, and it is not always reliable.

If overloading is needed, please try to use optional argument, or use generic argument (e.g LuaRef) that you can dispatch by yourself.
