### ISSUE TITLE
How to require() a lua module in C++ and to LuaRef the returned table?

### ISSUE THREAD

**Issue by jinq0123** [SteveKChiu/lua-intf#129]
I need to call lua mod.foo().
require("mod") will return a table:

-- mod.lua
local M = {}
function M.foo() ... end
return M
-- end of mod.lua

If mod is global, I can do this in C++:
LuaRef foo(L, "mod.foo");
foo();

But without global mod, how can I require("mod") and then LuaRef the returned table in C++?

**Comment by stdgregwar** [comment]
Hello,

Require is a global function. So you can get it's luaref and do whatever you want with it.

`LuaRef require(L, "require");`
`LuaRef mod = require.call("mod");`
`--now mod contains the mod main table`

It's as simple as that.

**Comment by jinq0123** [comment]
Thanks!
