### ISSUE TITLE
How can I know the function name from LuaRef

### ISSUE THREAD

**Issue by ketoo** [SteveKChiu/lua-intf#145]
Example:

LuaRef func(L, "module.method");
func(1, "yes", true);

Now I want to get the method name "module.method" from the object func, I got a function named typeName() from the class LuaRef, but it just returned the string "function".

Is there have an interface to achieve this goal which like below?

char* method = func.functionName(); //the content of method is "module.method"

**Comment by SteveKChiu** [comment]
It is not possible with LuaIntf, you need to write your own lookup code.

**Comment by ketoo** [comment]
Thanks for your reply.

May I compare the pointer of the function to know the name? For instance as below:

Lua code:
`script_module:add_class_cb("Player", self, self.class_common_event);`

C++ code:
`bool NFCLuaScriptModule::AddClassCallBack(std::string& className, const LuaIntf::LuaRef& luaRef, const LuaIntf::LuaRef& luaRef1)
{
if (luaRef.isTable())
		{
			for (auto itr = luaRef.begin(); itr != luaRef.end(); ++itr)
			{
				const LuaIntf::LuaRef& key = itr.key();

				const std::string& sKey = key.toValue<std::string>();
				const LuaIntf::LuaRef& val = itr.value();
				if (val.isFunction() && luaRef1.isFunction() && val.toPtr() == luaRef1.toPtr())
				{
                                        //now I know the functiona name is: class_common_event
					std::cout << sKey << " got it " << std::endl;
				}
			}
		}
}`

**Comment by ketoo** [comment]
Thanks for your great help! This makes the code look good and easy to maintain.
Now I solved my pain! 
Thank you again.
