### ISSUE TITLE
Can you add some usefull modules?

### ISSUE THREAD

**Issue by TheAifam5** [SteveKChiu/lua-intf#56]
Hi,
1. Function return all members of script (locals, globals and functions name, class names and class members and parameters) for AutoComplete system
2. Add support for lint code (checking errors etc)

**Comment by SteveKChiu** [comment]
1. It is better to use Lua's debug interface for that purpose, I am not sure what lua-intf can do for you about that. 

http://www.lua.org/manual/5.2/manual.html#lua_Debug

2. Would you give some example? What type of errors you want lua-intf to catch? lua-intf is template library, it can catch some runtime error or some compile-time checking (very-limit)? It probably can not do code-analysis like other lint tools.
