### ISSUE TITLE
[question] Serialisation of Lua objects?

### ISSUE THREAD

**Issue by SkyMarshal** [SteveKChiu/lua-intf#57]
I know this is possible to be done from the Lua side, but is there any straightforward way to do this from LuaIntf?  If not, do you have any suggestions?

**Comment by SteveKChiu** [comment]
I guess this means pure Lua object (table) ? It is not always possible for exported C++ objects.

If you already have Lua function to get the serialization form you needed, you can use LuaRef to access that function from C++.

If you want to do the serialization in C++, it has no mush difference from Lua, again using LuaRef will make the code much easier.

**Comment by SkyMarshal** [comment]
Wow, sorry.  Totally forgot about this.  Turns out, I can probably do it with the LuaState::isX functions.
