### ISSUE TITLE
Should this work?

### ISSUE THREAD

**Issue by nelson2005** [SteveKChiu/lua-intf#59]
LuaIntf::LuaContext lua_context;
lua_context.doString("my_variable=25");
LuaIntf::LuaRef globals(lua_context.state(), "_G");  
for(auto& e : globals) {
   std::string key = e.key<std::string>();
}

I get a core dump on the for() line.  It dumps in LuaTableIterator::next()

I"m using Lua 5.2.3 on Windows 7 and a slightly older (six months?) version of lua-intf that I hacked a little to work with VS2013.  It's entirely possible that I broke lua-intf, but I have been using it successfully.

Thanks

**Comment by SteveKChiu** [comment]
````
LuaIntf::LuaRef globals(lua_context.state(), "_G");
````
won't work, you will get NIL here. Please use

````
LuaIntf::LuaRef globals = LuaRef::globals(lua_context);
````

**Comment by nelson2005** [comment]
Thanks!
On Mon, Jan 26, 2015 at 9:11 PM, Steve K. Chiu <notifications@github.com> wrote:LuaIntf::LuaRef globals(lua_context.state(), "_G");


won't work, you will get NIL here. Please use

LuaIntf::LuaRef globals = LuaRef::globals(lua_context);
