### ISSUE TITLE
Access derived class' methods from a base class object

### ISSUE THREAD

**Issue by hasyimibhar** [SteveKChiu/lua-intf#6]
Sample classes:
```cpp
class Base {};

class Derived : public Base {
public:
   void foo();
};

// Their binding code

LuaIntf::LuaBinding(L).beginClass<Base>("Base")
.endClass();

LuaIntf::LuaBinding(L).beginExtendClass<Derived, Base>("Derived")
    .addFunction("foo", &Derived::foo)
.endClass();
```

Let's say I have an object of class `Derived`, but the pointer that keeps track of it is of type `Base`:
```cpp
Derived *a = new Derived();
// ...
Base *b = a;
```

I notice that if I push `b` to lua, I will not be able to call `foo` inside the script:
```cpp
Lua::setGlobal(L, "b", b);
```
```lua
b:foo() -- This fails
```

Is it possible to get it to work? (I think it's duck typing)
Thank you very much. :)

**Comment by l0ud** [comment]
Hi. I have similar problem.

```
class Base {};

class Derived : public Base {
public:
   void foo();
};

class Other : public Base {
public:
   void bar();
};
```

Let's say I have "factory" function that creates Derived and Other, but returns it as Base.

```
Base *factory() {

}

```

Is there something I can do?

**Comment by l0ud** [comment]
Hi. I have similar problem.

```
class Base {
public:
    virtual Type getType();
};

class Derived : public Base {
public:
   Type getType();
    void foo();
};

class Other : public Base {
public:
   virtual Type getType();
   void bar();
};
```
Let's say I have "factory" function that creates Derived and Other, but returns it as pointer to Base.
```
Base *factory() {
   if (sth) return new Derived();
   else return new Other();
}

```
I can easly bind that function, but I'll get only Base object, without ability to call foo() or bar(). In C++ i can cast Base to Other or Derived, after making sure that it's correct object using getType.

Is there any way I could make this cast in Lua? Maybe it's better to rewrite that function to put correct types on Lua stack if its possible? How?

Thanks in advance.

**Comment by SteveKChiu** [comment]
It would be better if you open new issue (or re-open the old issue), otherwise I may not see the comment.

If you want to push different Lua object in one method, the best way is to use `lua_CFunction` convention, or to use generic `LuaRef` as return value:

````c++
int factory(lua_State* L) {
    if (sth) {
        // this is actually a very bad example, the pointer will never be deleted
        // and you have memory leak here
        Lua::push(L, new Derived());

        // it would be better to use shared pointer
        // Lua::push(L, std::make_shared<Derived>());
    } else {
        // need to fix this too
        Lua::push(L, new Other());
    }
    return 1;
}
````

or 

````c++
LuaRef factory(lua_State* L) {
    if (sth) {
        return LuaRef::fromValue(L, std::make_shared<Derived>());
    } else {
        return LuaRef::fromValue(L, std::make_shared<Other>());
    }
}
````

**Comment by l0ud** [comment]
It'll do it. Thanks.

**Comment by SteveKChiu** [comment]
This should have been resolved, please reopen if you have more issues.
