### ISSUE TITLE
Problems with std::shared_ptr

### ISSUE THREAD

**Issue by wizofoz** [SteveKChiu/lua-intf#60]
Hi, when I try to compile even this simple code:

```
namespace LuaIntf
{
	LUA_USING_SHARED_PTR_TYPE(std::shared_ptr)
}

class A {
};

std::shared_ptr<A> returnA() {
    return std::shared_ptr<A>(new A);
}
std::shared_ptr<const A> returnConstA() {
    return std::shared_ptr<const A>(new A);
}

void do_the_bind(lua_State* L) {

	 LuaBinding(L).beginClass<A>("A")
	    .endClass();
	    LuaBinding(L).beginModule("utils")
	        .addFunction("returnA", &returnA)
	        .addFunction("returnConstA", &returnConstA)
	    .endModule();
}
```

The compiler give me this error:

../../Dependencies/Include/lua-intf/impl/LuaType.h: In instantiation of 'struct LuaIntf::LuaTypeMappingExists<std::shared_ptr<A> >':
../../Dependencies/Include/lua-intf/impl/LuaType.h:68:16:   required from 'struct LuaIntf::LuaType<std::shared_ptr<A> >'
../../Dependencies/Include/lua-intf/impl/CppInvoke.h:80:45:   required from 'static int LuaIntf::CppInvokeMethod<FN, R, P>::push(lua_State*, const FN&, std::tuple<_Args2 ...>&) [with FN = std::shared_ptr<A> (*)(); R = std::shared_ptr<A>; P = {}; lua_State = lua_State]'
../../Dependencies/Include/lua-intf/impl/CppBindModule.h:124:96:   required from 'static int LuaIntf::CppBindMethodBase<CHK, FN, IARG, R, P>::call(lua_State*) [with int CHK = 0; FN = std::shared_ptr<A> (*)(); int IARG = 1; R = std::shared_ptr<A>; P = {}; lua_State = lua_State]'
../../Dependencies/Include/lua-intf/impl/CppBindModule.h:447:61:   required from 'LuaIntf::CppBindModule& LuaIntf::CppBindModule::addFunction(const char*, const FN&) [with FN = std::shared_ptr<A> (*)()]'
..\Source\Core\../Lua/aeLuaIO.hpp:62:42:   required from here
../../Dependencies/Include/lua-intf/impl/LuaType.h:62:63: error: invalid use of incomplete type 'struct LuaIntf::LuaTypeMapping<std::shared_ptr<A>, void>'
     : decltype(LuaTypeExists(std::declval<LuaTypeMapping<T>>())) {};
                                                               ^
../../Dependencies/Include/lua-intf/impl/LuaType.h:42:8: error: declaration of 'struct LuaIntf::LuaTypeMapping<std::shared_ptr<A>, void>'
 struct LuaTypeMapping;
        ^

../../Dependencies/Include/lua-intf/impl/LuaType.h: In instantiation of 'struct LuaIntf::LuaTypeMappingExists<std::shared_ptr<const A> >':
../../Dependencies/Include/lua-intf/impl/LuaType.h:68:16:   required from 'struct LuaIntf::LuaType<std::shared_ptr<const A> >'
../../Dependencies/Include/lua-intf/impl/CppInvoke.h:80:45:   required from 'static int LuaIntf::CppInvokeMethod<FN, R, P>::push(lua_State*, const FN&, std::tuple<_Args2 ...>&) [with FN = std::shared_ptr<const A> (*)(); R = std::shared_ptr<const A>; P = {}; lua_State = lua_State]'
../../Dependencies/Include/lua-intf/impl/CppBindModule.h:124:96:   required from 'static int LuaIntf::CppBindMethodBase<CHK, FN, IARG, R, P>::call(lua_State*) [with int CHK = 0; FN = std::shared_ptr<const A> (*)(); int IARG = 1; R = std::shared_ptr<const A>; P = {}; lua_State = lua_State]'
../../Dependencies/Include/lua-intf/impl/CppBindModule.h:447:61:   required from 'LuaIntf::CppBindModule& LuaIntf::CppBindModule::addFunction(const char*, const FN&) [with FN = std::shared_ptr<const A> (*)()]'
..\Source\Core\../Lua/aeLuaIO.hpp:63:52:   required from here
../../Dependencies/Include/lua-intf/impl/LuaType.h:62:63: error: invalid use of incomplete type 'struct LuaIntf::LuaTypeMapping<std::shared_ptr<const A>, void>'
     : decltype(LuaTypeExists(std::declval<LuaTypeMapping<T>>())) {};
                                                               ^
../../Dependencies/Include/lua-intf/impl/LuaType.h:42:8: error: declaration of 'struct LuaIntf::LuaTypeMapping<std::shared_ptr<const A>, void>'
 struct LuaTypeMapping;

I'm using TDM-GCC 4.9.2 64 bit under Windows 7.

Thank you for help and for the amazing work you are doing!

**Comment by wizofoz** [comment]
I think I could have solved the problem specializing LuaTypeMapping:

```cpp
	template <typename T>
	struct LuaTypeMapping <std::shared_ptr<T>>
	{
	    using Type = std::shared_ptr<T>; //typename std::decay<T>::type;

	    static constexpr bool isConst = std::is_const<T>::value;

	    static void push(lua_State* L, const Type& p)
	    {
	        if (p == nullptr) {
	            lua_pushnil(L);
	        } else {
	            //CppObjectPtr::pushToStack(L, const_cast<Type*>(p), isConst);
	        	CppObjectSharedPtr<Type, T>::pushToStack(L, p, isConst);
	        }
	    }

	    static Type get(lua_State* L, int index)
	    {
	        return CppObject::get<Type>(L, index, isConst);
	    }

	    static Type opt(lua_State* L, int index, const Type& def)
	    {
	        if (lua_isnoneornil(L, index)) {
	            return def;
	        } else {
	            return CppObject::get<Type>(L, index, isConst);
	        }
	    }
	};
```
GC from Lua seems to be called correctly but I really have no idea if I have solved my problem correctly or if I made some bad mistake.

```lua
local my_shared_ptr_class = foo.create_shared_ptr_class()
my_shared_ptr_var = nil
collectgarbage() -- class destructor called
...
```

Thank you for any advice you can give me, best regards

**Comment by SteveKChiu** [comment]
The problem is LuaTypeMappingExists does not work well with GCC (clang works fine), I will fix that later. Or you can use the following version (prior to VS 2015 patch):

https://github.com/SteveKChiu/lua-intf/commit/439be2e1cb1791fb580fe42697fd62cc4121cd92

Specializing LuaTypeMapping can be a temperately workaround, but it is not necessary once the fix is ready.

**Comment by wizofoz** [comment]
I thought that could have been GCC fault. I'll wait your fix for GCC, thank you for your help!

**Comment by wizofoz** [comment]
It works perfectly now, thanks. 
Specializing LuaTypeMapping was not a good idea in the end and I had to use the 439be2e version until now.
