### ISSUE TITLE
Problem with CppBindClass::addConstant

### ISSUE THREAD

**Issue by wizofoz** [SteveKChiu/lua-intf#61]
I'm stuck with a problem with CppBindClass::setConstant but after several hours I haven't solved it yet.

CPP:
```cpp
.beginModule("myModule")
	.addConstant("myConst", 10) 
.endModule()

.beginClass<myClass>("myClass")
	.addConstant("myConst", 10) 
.endClass()
```

Lua:
```lua
print(myModule.myConst)  -- prints 10 correctly
print(myClass.myConst) -- Problem here: prints 'nil' value
print(myClass.___getters.myConst) -- prints 10 correctly
```

TDM GCC 4.9.2 64 bit under WIndows 7 with LuaJIT 2.0.3

Unfortunately it seems that I'm unable to solve this myself... any advice?
Thank you again very much

**Comment by SteveKChiu** [comment]
The meta method seems to have some problem, some changes lost during re-factoring the code, I will fix it ASAP.

**Comment by wizofoz** [comment]
Thank you for your prompt fix, it works perfectly! Now I can merge some modules that I had to use only for enums constants with classes

**Comment by inDigiNeous** [comment]
I am seeing this same issue. 

CPP

```c++
	LuaIntf::LuaBinding(_lua).beginClass<InputHandler>("InputHandler")
		.addConstructor(LUA_ARGS())
		.addFunction("keyHeld", 		&InputHandler::keyHeld)
		.addConstant("KEY_RIGHT", 		GLFW_KEY_RIGHT)
		.addConstant("KEY_LEFT", 		GLFW_KEY_LEFT)
		.addConstant("KEY_DOWN", 		GLFW_KEY_RIGHT)
		.addConstant("KEY_UP", 			GLFW_KEY_UP)
		.addConstant("constant",		10)
	.endClass();
```

lua

```
	print(input.KEY_RIGHT)
	print(input.___getters)
	print(#input.___getters)
```

output

```
nil
table: 0x7fb87953d040
0
```

Seems it is not adding these constants at all.
Mac Os X, Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Comment by l0ud** [comment]
@inDigiNeous
Maybe it's just example, but you're using "input" instead of class name "InputHandler" in your code.

**Comment by SteveKChiu** [comment]
Yes constant need to be accessed by class name, not by instance.
It is pretty much the same as static property.
