### ISSUE TITLE
[ASK] CLang + VS2013

### ISSUE THREAD

**Issue by TheAifam5** [SteveKChiu/lua-intf#62]
Hi,
Is possible to compile this using CLang + Visual Studio 2013?

http://sourceforge.net/projects/clangonwin/files/MsvcBuild/3.7/

EDIT: is Possible, but is needed add some options, read this!
http://lists.cs.uiuc.edu/pipermail/llvmdev/2014-August/075373.html

**Comment by SteveKChiu** [comment]
It looks like the issue has been resolved, please open new issue if there is anything I can help.
