### ISSUE TITLE
[Question] Lua and passing array as function argument

### ISSUE THREAD

**Issue by TheAifam5** [SteveKChiu/lua-intf#63]
Hi,
I have problem, how to pass array (from LUA) to C++ function?
And how to get array size and items?

LUA:
```
srututuArray({0xDA8208, 0x13A8, 0x4, 0x0018})
```

**Comment by EugeneKozlov** [comment]
Just write simple wrapper over std::vector like built-in Qt wrappers.

**Comment by SteveKChiu** [comment]
You can use LuaRef to capture the Lua value, something like the following:

````c++
void srututuArray(LuaRef list)
{
    for (int i = 1, n = list.len(); i <= n; i++) {
        int item = list.get<int>(i);
        ...
    }
}
````

or you can use Lua::getList to convert LuaRef to std::vector (or other list containers):

````c++
void srututuArray(LuaRef ref)
{
    std::vector<int> list = Lua::getList<std::vector<int>>(ref);
    ...
}
````

**Comment by SteveKChiu** [comment]
This seems to be resolved, please open new issue if you have more questions.
