### ISSUE TITLE
Getting over 1600 errors

### ISSUE THREAD

**Issue by DCubix** [SteveKChiu/lua-intf#66]
Hey, I just found LuaIntf, but whether I try to compile my program, I get over 1600 errors.
Here's part of the output:
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\luaexception.h(30): error C3646: 'noexcept' : unknown override specifier
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\luaexception.h(39): error C3646: 'noexcept' : unknown override specifier
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\luaexception.h(43): error C3646: 'noexcept' : unknown override specifier
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\luaexception.h(48): error C3646: 'noexcept' : unknown override specifier
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\luatype.h(62): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\luatype.h(63) : see reference to class template instantiation 'LuaIntf::LuaTypeMappingExists<T>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\luatype.h(62): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\luatype.h(380): error C2146: syntax error : missing ';' before identifier 'LuaString'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\luatype.h(380): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\luastate.h(246): error C2146: syntax error : missing ';' before identifier 'LuaState'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\luastate.h(246): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\luaref.h(156): error C2146: syntax error : missing ';' before identifier 'LuaTableIterator'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\luaref.h(156): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\luaref.h(414): error C2146: syntax error : missing ';' before identifier 'LuaRef'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\luaref.h(414): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(32): error C2039: 'intmax_t' : is not a member of 'std'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(44): error C2039: 'intmax_t' : is not a member of 'std'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(101): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(105) : see reference to class template instantiation 'LuaIntf::CppArgTraits<T>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(101): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(102): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(102): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(102): error C2086: 'int LuaIntf::CppArgTraits<T>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(101) : see declaration of 'LuaIntf::CppArgTraits<T>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(103): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(103): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(103): error C2086: 'int LuaIntf::CppArgTraits<T>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(101) : see declaration of 'LuaIntf::CppArgTraits<T>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(104): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(104): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(104): error C2086: 'int LuaIntf::CppArgTraits<T>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(101) : see declaration of 'LuaIntf::CppArgTraits<T>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(111): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(112) : see reference to class template instantiation 'LuaIntf::CppArgTraits<LuaIntf::_opt<T>>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(111): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(114): error C2039: 'intmax_t' : is not a member of 'std'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(118): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(121) : see reference to class template instantiation 'LuaIntf::CppArgTraits<LuaIntf::_def<T,DEF_NUM,DEF_DEN>>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(118): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(119): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(119): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(119): error C2086: 'int LuaIntf::CppArgTraits<LuaIntf::_def<T,DEF_NUM,DEF_DEN>>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(118) : see declaration of 'LuaIntf::CppArgTraits<LuaIntf::_def<T,DEF_NUM,DEF_DEN>>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(120): error C2146: syntax error : missing ';' before identifier 'T'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(120): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(120): error C2086: 'int LuaIntf::CppArgTraits<LuaIntf::_def<T,DEF_NUM,DEF_DEN>>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(118) : see declaration of 'LuaIntf::CppArgTraits<LuaIntf::_def<T,DEF_NUM,DEF_DEN>>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(129): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(131) : see reference to class template instantiation 'LuaIntf::CppArgTraits<LuaIntf::_out<T>>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(129): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(130): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(130): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(130): error C2086: 'int LuaIntf::CppArgTraits<LuaIntf::_out<T>>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(129) : see declaration of 'LuaIntf::CppArgTraits<LuaIntf::_out<T>>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(139): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(140) : see reference to class template instantiation 'LuaIntf::CppArgTraits<LuaIntf::_ref<T>>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(139): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(148): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(150) : see reference to class template instantiation 'LuaIntf::CppArgTraits<LuaIntf::_ref_opt<T>>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(148): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(149): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(149): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(149): error C2086: 'int LuaIntf::CppArgTraits<LuaIntf::_ref_opt<T>>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(148) : see declaration of 'LuaIntf::CppArgTraits<LuaIntf::_ref_opt<T>>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(152): error C2039: 'intmax_t' : is not a member of 'std'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(158): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(162) : see reference to class template instantiation 'LuaIntf::CppArgTraits<LuaIntf::_ref_def<T,DEF_NUM,DEF_DEN>>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(158): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(159): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(159): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(159): error C2086: 'int LuaIntf::CppArgTraits<LuaIntf::_ref_def<T,DEF_NUM,DEF_DEN>>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(158) : see declaration of 'LuaIntf::CppArgTraits<LuaIntf::_ref_def<T,DEF_NUM,DEF_DEN>>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(160): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(160): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(160): error C2086: 'int LuaIntf::CppArgTraits<LuaIntf::_ref_def<T,DEF_NUM,DEF_DEN>>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(158) : see declaration of 'LuaIntf::CppArgTraits<LuaIntf::_ref_def<T,DEF_NUM,DEF_DEN>>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(161): error C2146: syntax error : missing ';' before identifier 'T'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(161): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(161): error C2086: 'int LuaIntf::CppArgTraits<LuaIntf::_ref_def<T,DEF_NUM,DEF_DEN>>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(158) : see declaration of 'LuaIntf::CppArgTraits<LuaIntf::_ref_def<T,DEF_NUM,DEF_DEN>>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(171): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(171): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(172): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(172): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(172): error C2086: 'int LuaIntf::CppArgTraits<lua_State*>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(171) : see declaration of 'LuaIntf::CppArgTraits<lua_State*>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(173): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(173): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(173): error C2086: 'int LuaIntf::CppArgTraits<lua_State*>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(171) : see declaration of 'LuaIntf::CppArgTraits<lua_State*>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(174): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(174): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(174): error C2086: 'int LuaIntf::CppArgTraits<lua_State*>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(171) : see declaration of 'LuaIntf::CppArgTraits<lua_State*>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(184): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(184): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(185): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(185): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(185): error C2086: 'int LuaIntf::CppArgTraits<LuaIntf::LuaState>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(184) : see declaration of 'LuaIntf::CppArgTraits<LuaIntf::LuaState>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(186): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(186): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(186): error C2086: 'int LuaIntf::CppArgTraits<LuaIntf::LuaState>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(184) : see declaration of 'LuaIntf::CppArgTraits<LuaIntf::LuaState>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(187): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(187): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(187): error C2086: 'int LuaIntf::CppArgTraits<LuaIntf::LuaState>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cpparg.h(184) : see declaration of 'LuaIntf::CppArgTraits<LuaIntf::LuaState>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppinvoke.h(30): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppinvoke.h(31) : see reference to class template instantiation 'LuaIntf::CppCouldBeLambda<FN>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppinvoke.h(30): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppinvoke.h(36): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppinvoke.h(37) : see reference to class template instantiation 'LuaIntf::CppCouldBeLambda<std::function<R(P...)>>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppinvoke.h(36): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(192): error C2275: 'T' : illegal use of this type as an expression
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(146) : see declaration of 'T'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(195) : see reference to class template instantiation 'LuaIntf::CppObjectValue<T>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(192): error C2144: syntax error : 'double' should be preceded by ')'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(192): error C3861: 'alignof': identifier not found
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(192): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(193): error C2144: syntax error : 'int' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(193): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(194): error C2144: syntax error : 'unsigned char' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(194): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(194): warning C4183: 'alignas': missing return type; assumed to be a member function returning 'int'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(194): error C2327: 'LuaIntf::CppObjectValue<T>::MAX_PADDING' : is not a type name, static, or enumerator
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(194): error C2065: 'MAX_PADDING' : undeclared identifier
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(296): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(298) : see reference to class template instantiation 'LuaIntf::CppObjectTraits<T>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(296): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(297): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(297): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(297): error C2086: 'int LuaIntf::CppObjectTraits<T>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(296) : see declaration of 'LuaIntf::CppObjectTraits<T>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(375): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(397) : see reference to class template instantiation 'LuaIntf::LuaClassMapping<T,IS_CONST,IS_REF>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(375): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(376): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(376): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(376): error C2086: 'int LuaIntf::LuaClassMapping<T,IS_CONST,IS_REF>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(375) : see declaration of 'LuaIntf::LuaClassMapping<T,IS_CONST,IS_REF>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(377): error C2144: syntax error : 'bool' should be preceded by ';'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(377): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(377): error C2086: 'int LuaIntf::LuaClassMapping<T,IS_CONST,IS_REF>::constexpr' : redefinition
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(375) : see declaration of 'LuaIntf::LuaClassMapping<T,IS_CONST,IS_REF>::constexpr'
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(410): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(434) : see reference to class template instantiation 'LuaIntf::LuaTypeMapping<T*,void>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppobject.h(410): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppbindclass.h(151): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppbindclass.h(182) : see reference to class template instantiation 'LuaIntf::CppBindClassMethodBase<CHK,T,IS_PROXY,IS_CONST,FN,R,P...>' being compiled
1>c:\users\diego\dropbox\diego\thegameengine\depends\luaintf\impl\cppbindclass.h(151): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
...
I didn't find any info about this, so I'm posting this here... I hope someone can help me!

**Comment by EugeneKozlov** [comment]
Throw your compiler into trash

**Comment by SteveKChiu** [comment]
You need C++11 compilers, that means:

1. clang 3.3 or later
2. g++ 4.8 or later
3. visual studio c++ 2015 preview or later

Visual studio c++ 2013 or earlier version will not work.

**Comment by DCubix** [comment]
Ouch! that's not a good thing. I wanted to use std::vector or std::initializer_list as lua tables, and this project was perfect for it!
I guess I'm going back to LuaBridge, well, unless you guys have any other good alternatives that support what I want :P

**Comment by TheAifam5** [comment]
You can use CodeLite + Clang + TDM headers. Works awesome ;)
