### ISSUE TITLE
[Question] Correct QObject* mapping

### ISSUE THREAD

**Issue by CuriousCitizen** [SteveKChiu/lua-intf#68]
Hello, Steve.
Can you give me a hint about correct type mapping of QObject* (and pointer types in general)?
I need this to be able to use QObjectList, which is typedef for QList<QObject*>.
My implementation is:

``` cpp
template <>
struct LuaTypeMapping <QObject*>
{
    static void push(lua_State* L, const QObject* const & object)
    {
        Lua::push(L, object);
    }

    static QObject* get(lua_State* L, int index)
    {
        return reinterpret_cast<QObject*>(lua_tointeger(L, index));
    }

    static QObject* opt(lua_State* L, int index, const QObject*& def)
    {
        return lua_isnoneornil(L, index) ? const_cast<QObject*>(def) : get(L, index);
    }
};
```

This works, but I don't like this solution. What is wrong here (except lua_tointeger(), I know this is 32-bit only)?

**Comment by SteveKChiu** [comment]
Please try to use lightuserdata, lua_pushlightuserdata and lua_touserdata would do a better job.

````c++
template <>
struct LuaTypeMapping <QObject*>
{
    static void push(lua_State* L, const QObject* object)
    {
        lua_pushlightuserdata(L, const_cast<QObject*>(object));
    }

    static QObject* get(lua_State* L, int index)
    {
        return reinterpret_cast<QObject*>(lua_touserdata(L, index));
    }

    static QObject* opt(lua_State* L, int index, const QObject* def)
    {
        return lua_isnoneornil(L, index) ? const_cast<QObject*>(def) : get(L, index);
    }
};
````

Or you can simply export QObject, this will enable you to use `QObject*`, `const QObject&` and  `QObject&`

````c++
LuaBinding(L).beginClass<QObject>("QObject").endClass();
````

**Comment by CuriousCitizen** [comment]
Thank you, exporting object and adding LUA_USING_LIST_TYPE_X(QObjectList) works fine for me.

**Comment by SteveKChiu** [comment]
This seems to be resolved, please open a new one if you have more issues.
