### ISSUE TITLE
multiple results std::tuple template error

### ISSUE THREAD

**Issue by Skomski** [SteveKChiu/lua-intf#69]
std::tuple<bool, int> SliderInt(const char* label, int v, int min, int max) {
		bool changed = ImGui::SliderInt(label, &v, min, max);
		return std::tuple<bool, int>(changed, v);
	}

results in:

     Error  C2783	'int LuaIntf::CppInvokeMethod<FN,R,LuaIntf::CppArgHolder<const char   *>,LuaIntf::CppArgHolder<int>,LuaIntf::CppArgHolder<int>,LuaIntf::CppArgHolder<int>>::pushTuple(lua_State *,const std::tuple<bool,int> &)': could not deduce template argument for 'RV0'
     Lua-intf\luaintf\impl\CppInvoke.h	147

**Comment by SteveKChiu** [comment]
What compiler did you use?

**Comment by Skomski** [comment]
Visual Studio 2015 RC

Am Freitag, 1. Mai 2015 schrieb Steve K. Chiu :

> What compiler did you use?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SteveKChiu/lua-intf/issues/69#issuecomment-98045234>.
>


-- 

Kind regards,

Karl Skomski

**Comment by SteveKChiu** [comment]
I don't have access to VS 2015 RC, but I figure out it may be due to issue of template terminate function. Please try add`template <>` to line 149 of Lua-intf\luaintf\impl\CppInvoke.h, it will look like the following:
````c++
    template <>
    static int pushTuple(lua_State*, const std::tuple<RP...>&)
    {
        return 0;
    }
````

Please let me know if it works.

**Comment by SteveKChiu** [comment]
Please help to test the new commit.

**Comment by Skomski** [comment]
thank you -  fixed
