### ISSUE TITLE
Function with container

### ISSUE THREAD

**Issue by makroid** [SteveKChiu/lua-intf#70]
Your lua-intf looks very interesting!
How do you bind a (member) function that has as argument a vector (or any other C++ container), e.g.
`float calc_mean(const std::vector<float>& ar);`
or that returns a container:
`std::vector<Person> get_persons_of_age(int age);`
where "Person" is any user defined class?
Thanks.

**Comment by SteveKChiu** [comment]
To use container as Lua table, you need to first add it to lua-intf, it should be as easy as :
````c++
    namespace LuaIntf
    {
        LUA_USING_LIST_TYPE(std::vector)
    }
````

The above will enable `std::vector<float>` immediately, if you need to use custom class, you need to export the class by the following:
````c++
LuaBinding(L).beginClass<Person>("Person")
....
.endClass();
````

After that, you are able to use `std::vector<Person>` as well.

**Comment by SteveKChiu** [comment]
This seems have been resolved, please open new issue if needed.
