### ISSUE TITLE
Problem with getVariant(L, index)

### ISSUE THREAD

**Issue by chenjiansysu** [SteveKChiu/lua-intf#72]
**Lua**

    return {x=1, y={a=2}}

**CPP**
    
    LuaIntf::Lua::getVariant(L, -1).toMap()
The program crashes!

PS: `getMap(lua_State* L, int index)`  can't work for negative index!!!

**Comment by chenjiansysu** [comment]
It works with the following modifcation.

    /**
    * Get STL-style map from Lua table at the given index.
    */
    template <typename MAP>
    inline MAP getMap(lua_State* L, int index)
    {
        luaL_checktype(L, index, LUA_TTABLE);
        MAP map;
        lua_pushvalue(L, index);
        lua_pushnil(L);
        while (lua_next(L, -2)) {
            typename MAP::key_type key = get<typename MAP::key_type>(L, -2);
            map[key] = pop<typename MAP::mapped_type>(L);
        }
        lua_pop(L, 1);
        return map;
    }

**Comment by SteveKChiu** [comment]
The index need to be converted to absolute index, please see the commit. Thanks.

**Comment by chenjiansysu** [comment]
Thanks!
