### ISSUE TITLE
Problem with Lua::getVariant(lua_State* L, int idx)

### ISSUE THREAD

**Issue by chenjiansysu** [SteveKChiu/lua-intf#73]
**CPP:**

    luaL_dostring(L, "return 'test'")
    QVariant v = Lua::getVariant(L, -1)

I got a lua error: ***unknown type, can not convert to variant***.

Modification:

    LUA_INLINE QVariant Lua::getVariant(lua_State* L, int idx)
    {
        int type = lua_type(L, idx);
        if (type == LUA_TNIL || type == LUA_TNONE) {
            return QVariant();
        } else if (type == LUA_TNUMBER) {
            return lua_tonumber(L, idx);
        } else if (type == LUA_TBOOLEAN) {
            return lua_toboolean(L, idx) != 0;
        } else if (type == LUA_TSTRING)  { // Get QString
            return QString::fromUtf8(lua_tostring(L, idx));
        } else if (luaL_callmeta(L, idx, "__tostring")) {
            size_t l;
            const char* s = lua_tolstring(L, -1, &l);
            if (!s) {
                luaL_error(L, "'tostring' must return a string");
                return QVariant();
            }
            QByteArray buf(s, l);
            lua_pop(L, 1);
            return buf;
        } else if (type == LUA_TTABLE) {
            if (luaL_len(L, idx) > 0) {
                return getList<QVariantList>(L, idx);
            } else {
                return getMap<QVariantMap>(L, idx);
            }
        } else {
            luaL_error(L, "unknown type, can not convert to variant");
            return QVariant();
        }
    }

**Comment by SteveKChiu** [comment]
OK, the string mapping is added. The lua string is converted into QByteArray, not QString. But you can always call QVariant::toString() to get the string.

**Comment by SteveKChiu** [comment]
And as of Qt5, the default encoding for conversion between QString and QByteArrat is UTF8 (unlike Qt 4.x which is using local encoding), so it is safe to mix QByteArray and QString.

**Comment by chenjiansysu** [comment]
Thank you very much!
