### ISSUE TITLE
Lua Compiled as C++ but using LongJmp

### ISSUE THREAD

**Issue by TheAifam5** [SteveKChiu/lua-intf#74]
Hi,
I have Lua 5.3 compiled as C++ with option "/TP" in Visual Studio 2015 RC.
Really i dont have any idea what i making bad.. All compiling and linking good.. 

Why Lua still using longjmp?
"Exception thrown at 0x76df4598 (KernelBase.dll) in TestApp.exe: Microsoft C++ exception: lua_longjmp at memory location 0x00f4def4."

Here is code:
```
auto mState = LuaIntf::LuaState::newState();
				mState.openLibs();

				LuaBinding(mState)
					.beginClass<Memory>("Memory")
					.addStaticFunction("IsModuleLoaded", [](const char* moduleName) -> bool { HMODULE hM;
				return Memory::IsModuleLoaded(moduleName, hM); })

					.addStaticFunction("ReadChar", Memory::ReadChar)
					.addStaticFunction("ReadShort", Memory::ReadShort)
					.addStaticFunction("ReadInt", Memory::ReadInt)
					.addStaticFunction("ReadPtr", Memory::ReadPtr)
					.addStaticFunction("WriteChar", Memory::WriteChar)
					.addStaticFunction("WriteShort", Memory::WriteShort)
					.addStaticFunction("WriteInt", Memory::WriteInt)
					.addStaticFunction("WritePtr", Memory::WritePtr)
					.endClass();
				
				auto file = mState.doFile("C:/Script.lua");
				std::cout << "Test" << std::endl;
```

Lua file:
```
--Memory Test

print("MSVCP140D.DLL is not loaded!")

isModLoaded = Memory:IsModuleLoaded("MSVCP140D.DLL") --i know, bad maybe

print(isModLoaded)

--local isModLoaded = Memory:IsModuleLoaded("MSVCP140D.DLL")
--print("MSVCP140D.DLL is not loaded!")
--if isModLoaded then
--	print("MSVCP140D.DLL is loaded!")
--else
--	print("MSVCP140D.DLL is not loaded!")
--end
````

**Comment by SteveKChiu** [comment]
If you do not set LUAINTF_LINK_LUA_COMPILED_IN_CXX to 0, and is able to link the whole exe, then you are doing everything right.

And from the lua 5.3 source, lua is throwing lua_longjmp struct (yeah it is struct, not function), so I guess it is indeed throwing C++ exception, just the struct name is somewhat misleading.

BTW, you can throw your own exception by setting error handler with lua_atpanic, or use LuaContext which will set the error handler and throw LuaException.

**Comment by TheAifam5** [comment]
LUAINTF_LINK_LUA_COMPILED_IN_CXX is 1, because i want to use C++ Exceptions, not LongJmp.

Ok i check LuaContext

**Comment by SteveKChiu** [comment]
This seems to have been resolved, please open new issues if you have more questions.
