### ISSUE TITLE
Downcasting support

### ISSUE THREAD

**Issue by Schevv** [SteveKChiu/lua-intf#76]
Suppose I have

    class A { };
    class B : public A { int b; };

and a function

    A* func();

which might return an object of type B sometimes.

When I expose this to LUA, I will always get an object of type A and cannot upcast this to B, mainly because LUA does not support this kind of casting.
Du you intend to support this kind of downcasting (e.g. by adding a class method to cast or something similar) or is there a simpler way of doing this? Or is this simply out of scope of your library?

Thank you

**Comment by SteveKChiu** [comment]
It is possible to add downcast support, but in most cases it is better to avoid that in the first place.

Take the `A* func()` for example, you can rewrite it as the following:
````c++
LuaRef func(lua_State* L)
{
    if (...) {
        A* a = ....;
        return LuaRefValue(L, a);
        // or LuaRefObject<A>(L, ...) if you intend to create object inside userdata
    } else {
        B* b = ....;
        return LuaRefValue(L, b);
    }
}
````

Or if that is not possible (e.g. it is in collection, and you don't know the type), you can always add your own cast function in the base class:

````c++
LuaBinding(L).beginClass<A>("a")
    .addFunction("asB", [] (A* a) {
        return dynamic_cast<B*>(a);
    })
....
    .endClass()
````

Even I add the downcast later, it won't use dynamic_cast, and that could be dangerous for your app.

**Comment by SteveKChiu** [comment]
Please open new issue if you have more questions
