### ISSUE TITLE
Call c function from lua with non-POD pointer argument

### ISSUE THREAD

**Issue by c0ffeeartc** [SteveKChiu/lua-intf#77]
Things work fine through Lua C API int func(lua_State* l), but is there a better solution?
Here is how my code looks like:

    void func(UserType* uT) {}
    void printInt(int x) {printf("x == %d\n", x);}

    LuaIntf::LuaBinding(*_state)
        .beginModule("utils")
            .addFunction("func",     LUA_FN(void, func,     UserType*))
            .addFunction("printInt", LUA_FN(void, printInt, int))
        .endModule();

    UserType uT;
    _state->loadFile("script.lua");
    _state->pushLightUserData(&uT);
    _state->call(1,0);

And in Lua

    local uT = ...
    printInt(123) -- prints 'x == 123'
    func(ut)      -- crashes

What's the right way to call func(UserType*) from Lua, if possible?

**Comment by SteveKChiu** [comment]
You need to register `UserType` to `lua-intf`, otherwise `lua-intf` does not know to deal with the mapping.
````c++
LuaBinding(L).beginClass<UserType>("UserType")
  ....
   .endClass();
````

Another option is to create `LuaTypeMapping` if UserType is very simple and common, you can see the readme for how to create the mapping.

**Comment by c0ffeeartc** [comment]
Wow, it's great. After binding class and pushing its pointer with regular push it works flawlessly.
