### ISSUE TITLE
Does Lua-inf support dynamic link?

### ISSUE THREAD

**Issue by yuntang** [SteveKChiu/lua-intf#79]
I want to dynamically link the C++ module to lua. Is it supported?

Thanks

Yun

**Comment by TheAifam5** [comment]
Try: LUAINTF_HEADERS_ONLY=0
And compile as dll.

LuaIntf is very small, good idea is intergrate it with main exe(or dll) and Lua compile as DLL.

**Comment by SteveKChiu** [comment]
I am not sure about the original questions, if you are talking linking lua-intf as dll, then doing `LUAINTF_HEADERS_ONLY=0` and compile the source is fine.

But if you are talking about dynamically load other dll, and link it to lua script, then `lua-intf` does nothing like that. You have to do it by exporting native OS call via `lua-intf`. `lua-intf` is mostly a tool to allow you to export native C++ functions to lua script, it won't do other things. Please refer readme for more info.

**Comment by yuntang** [comment]
Thanks.

Yun
