### ISSUE TITLE
Downcasting (pt 2)

### ISSUE THREAD

**Issue by Schevv** [SteveKChiu/lua-intf#80]
This is a follow-up to my original question (https://github.com/SteveKChiu/lua-intf/issues/76)

From your answer, I found a solution that works fine for me using RTTI. By knowing the actual class type of an object (through RTTI or similar means), a program can provide an alternative classID to LuaIntf.

A created a fork (https://github.com/Schevv/lua-intf) to demonstrate that approach. I know it is intrusive to use the classID, but more sophisticated approaches would mean bigger changes to the code base.

Feel free to have a look/use the code if you are interested (or ignore if not :)

**Comment by SteveKChiu** [comment]
Thanks, I got the idea. I think maybe I can cook this in the `extendClass`, so users don't have to write `LuaAutomaticDowncast` by themselves.

It will take some time though, I am busy in some other projects.

**Comment by SteveKChiu** [comment]
OK, now `lua-intf` has auto downcast support, user only need to add sub class with `.beginExtendClass` and `lua-intf` will take care of downcast if necessary.
