### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by 1aam2am1** [SteveKChiu/lua-intf#82]
How access to a elements in std::map, std::vector, std::list in lua. 
struct X
{
std::map<int32_t, std::string> tab;
}

...

LuaBinding(L)
.beginClass<X>("x")
.addConstructor()
.addVariableRef("tab", &X::tab)
.endClass();

... lua

local st = x()

st.tab[0] = "Nothing" //That inot work
st.tab[1] = "How?"

Edit a README.

**Comment by SteveKChiu** [comment]
By default, lua-intf does not export any container type, including std::map. You can use LUA_USING_MAP_TYPE, but that only works with std::map as value type, and certainly will not work with your sample code.

The only way to make it work is to export std::map by yourself (via `LuaBinding(L).beginClass<std::map<k, v>>("may_map")`), and you can not use index syntax, that has been reserved for member access, you have to export get or set methods.
