### ISSUE TITLE
const-ness of reference arguments is ignored

### ISSUE THREAD

**Issue by Schevv** [SteveKChiu/lua-intf#83]
Hi again.

When binding a function with a const reference argument, (e.g. `void func(const A&)`), LuaIntf seems to drop the const-qualifier.

Adding `std::remove_reference` to the `LuaClassMapping`-case in `LuaType` solves the problem (for my test case at least).

The full definition of `LuaType` below for reference:

    template <typename T>
    struct LuaType
    : std::conditional<
        std::is_class<typename std::decay<T>::type>::value
            && !LuaTypeMappingExists<typename std::decay<T>::type>::value,
        LuaClassMapping<typename std::decay<T>::type, std::is_const<typename std::remove_reference<T>::type>::value, std::is_reference<T>::value>,
        LuaTypeMapping<typename std::decay<T>::type>
    >::type {};

**Comment by SteveKChiu** [comment]
Thanks, I get it fixed in the new commit.
