### ISSUE TITLE
Problem pushing local value onto the stack

### ISSUE THREAD

**Issue by ibachar** [SteveKChiu/lua-intf#84]
Hi

I'm trying to bind my vector math(vec2, vec3, vec4) classes.
Specifically multiplication between a vector and a scalar.
I've encountered a problem and also have one question.
The problem is that when I try to push the result of the multiplication, it seems the result is
pushed by pointer to the object although the object is a local variable inside a function:

    template <typename T>
    int vec_mul(T *a, lua_State *L, LuaRef b)
    {	 
        T res(0.0f);
                    	
        if (b.type() == LuaTypeID::NUMBER)
        {
            res = *a * b.toValue<float>();
        }
        	
        Lua::push(L, res);
        return 1;
    }

and for my binding of vec3 for example:

    .beginClass<vec3>("vec3")
        .addConstructor(LUA_ARGS(float, float, float))
        .addVariable("x", &vec3::x)
        .addVariable("y", &vec3::y)
        .addVariable("z", &vec3::z)
        ...
        .addFunction("__mul", &vec_mul<vec3>)
        ...

It seems that the variable res is pushed by pointer.
If I change it to:

    Lua::push(L, res * 1.0f);

It works properly since res * 1.0f is now an rvalue. Is there a way to force pushing by value instead of by pointer?

As for my question, how can I support both pre and post multiplication by a scalar?
The above code handles post multiplication but pre multiplication means Lua calls the __mul function
with the first parameter being a number and the second parameter the vector

Thanks.

**Comment by ibachar** [comment]
Using std::move correctly pushes by value but I'm not sure if this is the correct solution as I don't fully understand move semantics yet

**Comment by SteveKChiu** [comment]
It looks like Lua::push should not use universal reference, that it will make the type inferred as lvalue reference (which is not quite right). I fix this in the new commit.

**Comment by ibachar** [comment]
Great, thanks for the prompt fix.
Do you have any ideas how I would bind pre and post multiplication?
Is it possible to bind cfunctions as member functions that doesn't require the first parameter to be a pointer to the class? This way I would be able to catch both cases where the first or the second parameter is a vector

**Comment by SteveKChiu** [comment]
I am afraid it is not possible with lua operator, since the operator (meta method) must be attached to userdata or table, there is no standalone infix method you can override. You need to either convert the constant to userdata, or add method to the vector.

**Comment by ibachar** [comment]
I think it is possible because I successfully did it with LuaBridge(+small modifications of mine). In case you have an operator where the first operand is a number and the second operand does have a __mul function, Lua will invoke the second operand's metamethod, passing the number as the first parameter and the table/userdata as the second (http://www.lua.org/pil/13.1.html)
What I need is a way to bind a Lua cfunction as a member function without the constraint that the first parameter must be a pointer to the member. Then, I would be able to check if the first parameter is a number or the vector

**Comment by SteveKChiu** [comment]
Interesting, I am not aware of this. Then I think it is possible after some modifications. Would you mind open a new issue for this? It is off topic from the original question; it would help other people if we put the issue under the correct topic.
