### ISSUE TITLE
Enable binding "regular" cfunctions as  member functions of a class 

### ISSUE THREAD

**Issue by ibachar** [SteveKChiu/lua-intf#86]
Hi,

Is it possible to add support to bind a cfunction as a member function without the constraint that the first parameter must be a pointer to the class?
This will allow me to implement arithmetic operators for my vector math and support both pre and post multiplication between a vector and a scalar (by inspecting the first parameter and checking whether it is a number or the vector)

Thanks

**Comment by SteveKChiu** [comment]
It is now possible to add static meta function to the object function table. And a new cast function `Lua::objectCast` can be used to test whether the value or LuaRef is an instance of the given class. For example:

````c++
static Vec mul(LuaRef lhs, LuaRef rhs)
{
    // 
    Vec* lhs_vec = Lua::objectCast<Vec>(lhs);
    if (lhs_vec) {
        ....
    }

    if (rhs.type() == LuaTypeID::NUMBER) {
        ....
    }
}

LuaBinding(L).beginClass<Vec>("Vec")
    .addMetaFunction("__mul", &mul_vec)
    ...
.endClass()
````

These should be enough to implement arithmetic operators for your case.

**Comment by ibachar** [comment]
Thanks. Works like a charm

**Comment by ibachar** [comment]
I checked the new objectCast function and it seems that when the object is of not the correct type an exception is thrown instead of silently retuning nullptr...
Is it possible to not throw the exception or maybe have a checkType function added to LuaRef or something similar?

**Comment by SteveKChiu** [comment]
It is a copy-and-paste error, objectCast should not raise lua error unless the class is not registered.

**Comment by ibachar** [comment]
Great, thanks for your support and quick fixes
