### ISSUE TITLE
Possible to anonymously call a class method via a LuaRef passed to C++?

### ISSUE THREAD

**Issue by demianmnave** [SteveKChiu/lua-intf#87]
Hi, I was wondering if it is possible to *anonymously* call a class method via a LuaRef passed to a function from Lua?  For example, I might have in Lua:

```lua
arg = MyObject.new()
wrapped(arg)

arg2 = MyOtherObject.new()
wrapped(arg2)
```

Then, from the wrapped function I would like to anonymously access a method in MyObject or MyOtherObject, without actually knowing which Object I have:

```cpp
void wrapped(LuaRef arg) {
   // Call a class method via 'arg', without actually knowing which type of Object 'arg' is ...
}
```

This would be possible if I could access the class metatable of the underlying object via 'arg', but the only relationship I can find between 'arg' and its class metatable is via the global table, keyed on the class ID of MyObject (or MyOtherObject).  Am I missing something?

Thanks!
Demian Nave

**Comment by SteveKChiu** [comment]
I suppose you want to call any object with given method name, it is much like this in Lua (with "my_method" as function name):
````lua
function wrapped(arg)
    arg:my_method()
end
````

It is pretty easy with LuaRef:
````c++
void wrapped(LuaRef arg) {
   arg.dispatch("my_method") // just as arg:my_method()
}
```

It is no need to know the class id whether it is in lua or in LuaRef.

**Comment by SteveKChiu** [comment]
On second thought, I am not sure what you really want to call, member function or class static function?

In case you want to call the class static function, now I export the ".class" to allow object to access its own class. In your example, if you want to call the "new" method (which is static method), you can now do this in lua:

````lua
function wrapped(arg)
    arg.class.new()
end
````

or in LuaRef:

````c++
void wrapped(LuaRef arg) {
   arg.get("class").dispatchStatic("new") // just as arg.class.new()
}
````

**Comment by demianmnave** [comment]
It's useful to have both options, thanks for the quick update.
