### ISSUE TITLE
Access local functions of script and place into LuaRef*

### ISSUE THREAD

**Issue by MattGuerrette** [SteveKChiu/lua-intf#90]
Is it possible to run a script defining local functions and then access them and store them in LuaRef* objects to be called from C++?

**Comment by SteveKChiu** [comment]
You need a way to store the function, most likely via callback function.

If the function is local, then you can not access it from C++ by name, you have to explicitly pass the local variable to C++, such as pass it as parameter to the exported C++ function.

If you are using doString, then you can `return` the object (whether it is function or not), and using LuaRef to catch the return value.

**Comment by MattGuerrette** [comment]
Thats fine, I settled on having each script define the same global 3 functions that are used by the game engine, and I defined them in a global table that is created for each script.
