### ISSUE TITLE
Way to send pointer to lua table from C++ into Lua?

### ISSUE THREAD

**Issue by MattGuerrette** [SteveKChiu/lua-intf#92]
I was wondering if there is a way to bind a function to lua that would return a lua table?

Something like

     _myTable = object:GetTable();

where GetTable is the function exposed to lua.

**Comment by SteveKChiu** [comment]
You can have function return LuaRef, for example:

````c++
LuaRef GetTable() {
    ...
}
````

Or you can enable STL mapping, then return std::vector or std::map:

````c++
    namespace LuaIntf
    {
        LUA_USING_LIST_TYPE(std::vector)
        LUA_USING_MAP_TYPE(std::map)
    }

    std::map GetTable() {
       ...
    }
````

**Comment by SteveKChiu** [comment]
It seems to be resolved.
