### ISSUE TITLE
Inheritance with shared pointers

### ISSUE THREAD

**Issue by l0ud** [SteveKChiu/lua-intf#94]
Hi. I have class A, B, C, when B is extending class A.
Class C has a method that takes argument std::shared_ptr<A>.

I want to have class B created by lua so I exported its constructor using:
```
LuaBinding(state).beginExtendClass<B, A>("B")
.addConstructor(LUA_SP(std::shared_ptr<B>), LUA_ARGS(...))
...
```

Class A is exported too, but without constructor.

To be sure, I added
```
namespace LuaIntf {
	LUA_USING_SHARED_PTR_TYPE(std::shared_ptr)
}
```
before both declarations.

Every time I call method in class C from lua, I get lua-intf error: "unknown class, you need to register..."

Can you give some hint what I'm missing?

**Comment by SteveKChiu** [comment]
You need to provide C++ declaration and LuaBinding code for the A, B, C  classes, for the methods you have trouble.

The constructor binding only affect constructors, it is not related to other shared_ptr usage. For example, you can freely use `shared_ptr<A>` or `shared_ptr<C>`, as long as you have `LUA_USING_SHARED_PTR_TYPE(std::shared_ptr)`.

So the problem must be in the method declaration, most likely you forgot to create class binding for some of the arguments or return values.

**Comment by l0ud** [comment]
So, there are bindings from my code:

```
LuaBinding(state).beginClass<A>("A")
.addProperty("sth", &A::getSth, &A::setSth)
.addPropertyReadOnly("sth2", &A::getSth2)
.addFunction("doSth", &A::doSth)
.addConstant("SOME_DEF", some_defs::SOME_DEF)
.endClass();

LuaBinding(state).beginExtendClass<B, A>("B")
.addConstructor(LUA_SP(std::shared_ptr<B>), LUA_ARGS(NeededPointerOfOtherClass *))
.addFunction("bindCallback", &B::bindCallback)
.addConstant("SOME_DEF", other_defs::SOME_DEF)
.endClass();

LuaBinding(state).beginExtendClass<C, A>("C")
.addConstructor(LUA_SP(std::shared_ptr<C>), LUA_ARGS(NeededPointerOfOtherClass *, SomeEnum, uint8))
.addFunction("connectA", &C::connectA, LUA_ARGS(uint8, std::shared_ptr<A>))
.addFunction("getConnectedA", &C::getConnectedA, LUA_ARGS(uint8))
.endClass();
```
Sorry, I had to change method names.

In previous post I overlooked that C class is extending A too.

Method I have the problem with, has following prototype:
```
void connectA(uint8 port, std::shared_ptr<A> toConnect);
```

**Comment by SteveKChiu** [comment]
The code looks fine to me, I have no idea why it has problem.
Please try `#define LUAINTF_AUTO_DOWNCAST 0` before include LuaIntf.h, see if it make any difference.

**Comment by l0ud** [comment]
No, it doesn't.

**Comment by SteveKChiu** [comment]
I am not sure if C is in different compile unit (file) or not, maybe you have not included `LUA_USING_SHARED_PTR_TYPE(std::shared_ptr)` before define C?

**Comment by l0ud** [comment]
Bindings for each class are implemented as single method with common name. Then I use template to automatically call that methods for each class used in my lua state.

I added 

```
namespace LuaIntf {
	LUA_USING_SHARED_PTR_TYPE(std::shared_ptr)
}
```
before that method definitions for classes A, B and C in my cpp files.

**Comment by SteveKChiu** [comment]
I am not sure where you put the `LUA_USING_SHARED_PTR_TYPE(std::shared_ptr)`, you have to put it  in the root namespace, or you just created nested namespace that will not work.

**Comment by l0ud** [comment]
The following code:
```
namespace LuaIntf {
	LUA_USING_SHARED_PTR_TYPE(std::shared_ptr)
}
```
is in root namespace for each cpp file. It does not compile without LuaIntf namespace definition.

**Comment by SteveKChiu** [comment]
The last thing I can think about is maybe you are using the wrong syntax for lua method call, it need to use ':' not '.' for object methods.

**Comment by l0ud** [comment]
It's not that simple I'm afraid.

Lua code:
```
_bclass = B(otherPointer)
_bclass:bindCallback(_otherLuaFunction)
local cclass = C(otherPointer, 2, 4)
bclass:connectA(1, cclass)
```

It fails at this line:
```
bclass:connectA(1, cclass)
```

The same lua code worked without any modifications, I just changed raw to shared pointers because that local object getting destroyed by gc.

**Comment by SteveKChiu** [comment]
Where did bclass come from? It is not _bclass or cclass in your example.

**Comment by l0ud** [comment]
I made a mistake quicly edited my post. You must read the old version, sorry.

**Comment by l0ud** [comment]
Still no progress... To simplify, I registered a constructor to A class and tried to use connectA using A instance (instead of B). Also, I changed C class so it's no longer registered as extension to A.
Still the same error.

Stacktrace of a breakpoint in a place where this error is thrown:
```
LuaIntf::CppObject::getObject
LuaIntf::CppObject::getObject<std::shared_ptr<A> >
LuaIntf::LuaClassMapping<std::shared_ptr<A>, false, false>::get
LuaIntf::CppArgInput<LuaIntf::CppArgTraits<std::shared_ptr<A> >, true, false, false>::get
LuaIntf::CppArg<std::shared_ptr<A> >::get
```

A is registered, otherwise I couldn't create its instance in lua.

**Comment by SteveKChiu** [comment]
Base on the back-trace, it seems the shared_ptr rule is not recognized, the second line should be:
````
LuaIntf::CppObject::getObject<A>
````

Otherwise it won't work. What compiler do you use for your project?

**Comment by l0ud** [comment]
GCC 4.9.2. Also tried with Visual 2015.

I tried to move that LUA_USING_SHARED_PTR_TYPE block directly to header file where I include lua-intf, so it's now defined in every cpp file using lua. And it works now.
It's very confusing as I carefully checked if that block was placed before "registering" method implementations in A, B, and C classes.
What is the best place to put that lua-intf macros?

**Comment by SteveKChiu** [comment]
The macro need to be placed for every file that may take share_ptr as parameter, not just the registering classes. For example if you have class D that take share_ptr<A> as function parameter, then you need to import LUA_USING_SHARED_PTR_TYPE too.

The best place to put the macro is in the header file, usually I create a new header file, such as "MyLuaIntf.h"; then include "LuaIntf.h" and include LUA_USING_SHARED_PTR_TYPE or other LUA_USING_xxx macro, as well as any custom type mapping. That will ensure the template specialization rule would compile properly.

**Comment by fordcars** [comment]
Hi, do we still have to use those macro every time we have function that takes a shared_ptr?

**Comment by SteveKChiu** [comment]
Just put it into the header files.
