### ISSUE TITLE
Pass nil from Lua to C++

### ISSUE THREAD

**Issue by 0xc0dec** [SteveKChiu/lua-intf#96]
Hi,

I'm having problems passing nils from Lua to my C++ code. For instance if I register a function
```
void f(int *i)
{
}
```
and then bind it
```
module.addFunction("f", &f);
```
then when calling it from Lua
```
module.f(nil)
```
I get Lua error `expect userdata, got nil`. Is there anything I'm doing wrong or is feature not supported?

**Comment by 0xc0dec** [comment]
Well, I suspect it's the legacy of LuaBridge :)

From LuaBridge docs:
> Passing nil to a C++ function that expects a pointer or reference.

**Comment by TheAifam5** [comment]
Also i have problem with that.. :( I hope @SteveKChiu repair that :p Just only wait :)

**Comment by SteveKChiu** [comment]
Another way is to use `_opt` to declare it as optional, so if you don't pass the argument, it will be nil automatically.

**Comment by 0xc0dec** [comment]
Thanks! I'll give it a try.
