### ISSUE TITLE
How to bind such function: bool SliderFloat(const char* label, float* v /*in_out*/); ?

### ISSUE THREAD

**Issue by bagobor** [SteveKChiu/lua-intf#97]
I'm trying to create lua bindings to imgui library.
This library uses return values and in_out parameters passed as pointers.

Is it possible to bind it somehow using lua_inf? 
Thanks for help! :+1:

**Comment by bagobor** [comment]
Thanks for reply!
Is std::tuple support to return multiple values from C++ to script or vice versa?

**Comment by SteveKChiu** [comment]
Yes you can to that, as described in the readme.
Also it is possible to do in/out parameters with reference, just not with pointers.

**Comment by SteveKChiu** [comment]
It seems to be resolved.
