### ISSUE TITLE
How to bind data type HWND and addConstructor

### ISSUE THREAD

**Issue by nghack** [SteveKChiu/lua-intf#99]
Thanks for help!

**Comment by MattGuerrette** [comment]
isn't HWND defined as void* ?

**Comment by nghack** [comment]
YES! but how to bind it?
I wan't to bind this function : HWND WINAPI GetParent( __in HWND hWnd )

**Comment by nghack** [comment]
Sorry, it defined as this:
struct HWND__ {int unused;}
typedef HWND__  *HWND;
